# Generated by Django 3.0.3 on 2020-11-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='name',
            new_name='fname',
        ),
    ]
