# Generated by Django 3.0.3 on 2020-11-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201108_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
