# Generated by Django 3.0.3 on 2020-11-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_queries_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='time',
            field=models.DateTimeField(default=(2020, 11, 10, 20, 31, 21, 1, 315, 0)),
        ),
    ]
