# Generated by Django 3.0.3 on 2020-11-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201110_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
