# Generated by Django 3.0.3 on 2020-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201110_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('background_color1', models.CharField(max_length=10)),
                ('background_color2', models.CharField(max_length=10)),
            ],
        ),
    ]
